server:
  port: 7003

eureka:
  instance:
    hostname: eureka7003.com

  client:
    register-with-eureka: false # 是否注册自己
    fetch-registry: false # 获取注册，false表示自己为注册中心
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/